# Copyright (c) Meta Platforms, Inc. and affiliates.
# modfied by Xudong Wang based on https://github.com/lucasb-eyer/pydensecrf/blob/master/pydensecrf/tests/test_dcrf.py and third_party/TokenCut

import numpy as np
import pydensecrf.densecrf as dcrf
import pydensecrf.utils as utils
import torch
import torch.nn.functional as F
import torchvision.transforms.functional as VF

MAX_ITER = 10
POS_W = 7 
POS_XY_STD = 3
Bi_W = 10
Bi_XY_STD = 50 
Bi_RGB_STD = 5

# CRFs are a type of probabilistic graphical model used for structured prediction. In image processing, they are often employed 
# for tasks like image segmentation, where the goal is to assign a label to each pixel in an image in a way that takes into account 
# both the individual pixel's information and the contextual information from neighboring pixels.
# DenseCRF is a specific type of CRF that utilizes fully connected pairwise potentials. 
# This means that every pixel in the image can potentially interact with every other pixel,
# allowing for more detailed and refined segmentation results.

#DenseCRF considers both spatial (geometric) and appearance (color) information to improve the segmentation accuracy.

def densecrf(image : np.array, mask : np.array):
    # image is a 2D numpy array representing the input image.
    # mask is a binary mask indicating the foreground and background.
    h, w = mask.shape
    mask = mask.reshape(1, h, w); # (1, h, w)
    fg = mask.astype(float); # # (1, h, w)
    bg = 1 - fg; # (1, h, w)
    output_logits = torch.from_numpy(np.concatenate((bg,fg), axis=0)) # (1,h,w) cat (1,h,w) -> (2,h,w)

    H, W = image.shape[:2]
    image = np.ascontiguousarray(image); # (H, W, 3)
    
    output_logits: torch.Tensor = F.interpolate(output_logits.unsqueeze(0), size=(H, W), mode="bilinear").squeeze(); #(2, H, W)
    output_probs = F.softmax(output_logits, dim=0).cpu().numpy(); # (2, H, W)
    
    c = output_probs.shape[0]
    h = output_probs.shape[1]
    w = output_probs.shape[2]

    U = utils.unary_from_softmax(output_probs); # numpy : (c, H * W)
    U = np.ascontiguousarray(U); # (c, H * W)

    d = dcrf.DenseCRF2D(w, h, c);
    """  Unary potentials: represent the cost of assigning each pixel to a particular label (foreground or background).
                           These are derived from the softmax probabilities.
    """
    # Convert probabilities to unary potentials (energy values for each pixel label).
    d.setUnaryEnergy(U);
    """ Gaussian Potentials (pairwise potentials): 
        Consider the spatial closeness of pixels. Pixels that are closer together are more likely to have the same label.
    """
    # Consider the spatial closeness of pixels. Pixels that are closer together are more likely to have the same label.
    # sxy (standard deviation in XY plane): Controls the spatial proximity influence.
    # compat (compatibility): Defines the penalty for different labels.
    d.addPairwiseGaussian(sxy=POS_XY_STD, compat=POS_W);
    """ Bilateral Potentials (pairwise potentials): Consider both spatial closeness and color similarity. 
                                                    This helps to preserve object boundaries where there are color differences.
    """
    # sxy (spatial proximity standard deviation).
    # srgb (color similarity standard deviation).
    # compat (compatibility).
    d.addPairwiseBilateral(sxy=Bi_XY_STD, srgb=Bi_RGB_STD, rgbim=image, compat=Bi_W)

    # Inference is run for a specified number of iterations (MAX_ITER), resulting in the most probable label for each pixel.
    Q: list = d.inference(MAX_ITER) # len = H * W * c
    Q: np.array = np.array(Q).reshape((c, h, w)) # (c, H, W)
    # The final segmentation map (MAP) is generated by taking the label with the highest probability for each pixel after inference.
    MAP: np.array = np.argmax(Q, axis=0).reshape((h,w)).astype(np.float32);# (H, W)
    return MAP #[H,W]
